version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: argus-ai-backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/
      - ARTIFACT_PATH=/app/artifacts/
      - HF_HOME=/app/models
      - SENTENCE_TRANSFORMERS_HOME=/app/models
      - TOP_K=2000
      - RERANK_K=300
      - FINAL_K=100
    volumes:
      - ../artifacts:/app/artifacts
      - ../models:/app/models
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
